#server:
#  port: 11000
#spring:
#  application:
#    name: gateway-service
#  redis:
#    host: 192.168.1.201
#    port: 6379
#    password: 123456
#    database: 0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.1.201:8848
#        namespace: 4de4b457-1250-40fc-a274-85a029095374
#        group: pre.release
#        cluster-name: GuangZhou
#        metadata:
#          service-version: 2020.1210
#          api-info: The lastest Api.
#    # 网关配置
#    gateway:
#      discovery:
#        locator:
#          enabled: false
#      routes:
#        - id: auth-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#        - id: article-route
#          uri: lb://article-service
#          predicates:
#            - Path=/article/**
#          filters:
#            - StripPrefix=1
#            # 开启限流
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器Bean的名称
#                key-resolver: '#{@uriKeyResolver}'
#                # 令牌桶填充速率：每秒放2个；也就是说，每个用户每秒最多只能执行2个请求
#                redis-rate-limiter.replenishRate: 2
#                # 令牌桶最大容量值：4个
#                redis-rate-limiter.burstCapacity: 4
#        - id: question-route
#          uri: lb://question-service
#          predicates:
#            - Path=/question/**
#          filters:
#            - StripPrefix=1
#            # 开启限流
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器Bean的名称
#                key-resolver: '#{@uriKeyResolver}'
#                # 令牌桶填充速率：每秒放2个；也就是说，每个用户每秒最多只能执行2个请求
#                redis-rate-limiter.replenishRate: 2
#                # 令牌桶最大容量值：4个
#                redis-rate-limiter.burstCapacity: 4
#        - id: system-route
#          uri: lb://system-service
#          predicates:
#            - Path=/system/**
#          filters:
#            - StripPrefix=1
#            # 开启限流
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器Bean的名称
#                key-resolver: '#{@uriKeyResolver}'
#                # 令牌桶填充速率：每秒放2个；也就是说，每个用户每秒最多只能执行2个请求
#                redis-rate-limiter.replenishRate: 2
#                # 令牌桶最大容量值：4个
#                redis-rate-limiter.burstCapacity: 4
#        - id: goods-route
#          uri: lb://goods-service
#          predicates:
#            - Path=/goods/**
#          filters:
#            - StripPrefix=1
#            # 开启限流
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器Bean的名称
#                key-resolver: '#{@uriKeyResolver}'
#                # 令牌桶填充速率：每秒放2个；也就是说，每个用户每秒最多只能执行2个请求
#                redis-rate-limiter.replenishRate: 2
#                # 令牌桶最大容量值：4个
#                redis-rate-limiter.burstCapacity: 4
