apiVersion: v1
kind: Namespace
metadata:
  name: blog-business
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-system
  namespace: blog-business
  labels:
    ms/blog: blog-system
spec:
  replicas: 2
  selector:
    matchLabels:
      ms/blog: blog-system
  template:
    metadata:
      labels:
        ms/blog: blog-system
    spec:
      restartPolicy: Always
      containers:
        - image: 192.168.1.190:88/ms-blog/blog-system:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: blog-system
          ports:
            - containerPort: 11400
              name: port-11400
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-system
  namespace: blog-business
  labels:
    ms/blog: blog-system
spec:
  type: NodePort
  ports:
    - name: port-11400-blog-system
      port: 11400
      protocol: TCP
      nodePort: 31400
      targetPort: 11400
  selector:
    ms/blog: blog-system
