apiVersion: v1
kind: Namespace
metadata:
  name: blog-business
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-gateway
  namespace: blog-business
  labels:
    ms/blog: blog-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      ms/blog: blog-gateway
  template:
    metadata:
      labels:
        ms/blog: blog-gateway
    spec:
      restartPolicy: Always
      containers:
        - image: 192.168.1.190:88/ms-blog/blog-gateway:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: blog-gateway
          ports:
            - containerPort: 11000
              name: port-11000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-gateway
  namespace: blog-business
  labels:
    ms/blog: blog-gateway
spec:
  type: NodePort
  ports:
    - name: port-11000-blog-gateway
      port: 11000
      protocol: TCP
      nodePort: 31000
      targetPort: 11000
  selector:
    ms/blog: blog-gateway
