apiVersion: v1
kind: Namespace
metadata:
  name: blog-business
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-article
  namespace: blog-business
  labels:
    ms/blog: blog-article
spec:
  replicas: 2
  selector:
    matchLabels:
      ms/blog: blog-article
  template:
    metadata:
      labels:
        ms/blog: blog-article
    spec:
      restartPolicy: Always
      containers:
        - image: 192.168.1.190:88/ms-blog/blog-article:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: blog-article
          ports:
            - containerPort: 11200
              name: port-11200
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-article
  namespace: blog-business
  labels:
    ms/blog: blog-article
spec:
  type: NodePort
  ports:
    - name: port-11200-blog-article
      port: 11200
      protocol: TCP
      nodePort: 31200
      targetPort: 11200
  selector:
    ms/blog: blog-article
