apiVersion: v1
kind: Namespace
metadata:
  name: blog-business
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-auth
  namespace: blog-business
  labels:
    ms/blog: blog-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      ms/blog: blog-auth
  template:
    metadata:
      labels:
        ms/blog: blog-auth
    spec:
      restartPolicy: Always
      containers:
        - image: 192.168.1.190:88/ms-blog/blog-oauth2:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: blog-auth
          ports:
            - containerPort: 11500
              name: port-11500
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-auth
  namespace: blog-business
  labels:
    ms/blog: blog-auth
spec:
  type: NodePort
  ports:
    - name: port-11500-blog-auth
      port: 11500
      protocol: TCP
      nodePort: 31500
      targetPort: 11500
  selector:
    ms/blog: blog-auth
